call plug#begin('~/.vim/plugged')
Plug 'itchyny/vim-gitbranch'
Plug 'jiangmiao/auto-pairs'
Plug 'myusuf3/numbers.vim'
Plug 'neoclide/coc-snippets'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'fatih/vim-go'
 
Plug 'morhetz/gruvbox'
Plug 'bradfitz/goimports'
Plug 'OmniSharp/omnisharp-vim'
Plug 'mxw/vim-jsx'
call plug#end()


colorscheme gruvbox
set background=dark
imap <C-l> <Plug>(coc-snippets-expand)
imap <C-l> <Plug>(coc-snippets-expand)
let g:coc_snippet_next = '<c-j>'
let g:coc_snippet_prev = '<c-k>'
xmap <leader>x  <Plug>(coc-convert-snippet)


inoremap <silent><expr> <TAB>
      \ pumvisible() ? coc#_select_confirm() :
      \ coc#expandableOrJumpable() ? "\<C-r>=coc#rpc#request('doKeymap', ['snippets-expand-jump',''])\<CR>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()


function! s:check_back_space() abort
    let col = col('.') - 1
    return !col || getline('.')[col - 1]  =~# '\s' 
endfunction

syntax on
set encoding=UTF-8
set termencoding=utf8

set expandtab
set ruler
set wildmenu
set shiftwidth=4 
set tabstop=4
set softtabstop=4
set nobackup
set noswapfile
set t_Co=256
set clipboard=unnamedplus
set foldmethod=indent   
set foldnestmax=10
